sudo: required
services: 
    - docker

before_install:
    - docker build -t abhay14kumar/react-demo -f ./client/Dockerfile.dev ./client

script:
    - docker run abhay14kumar/react-demo npm test -- --coverage

after_success:
    - docker build -t abhay14kumar/multi-client-demo ./client
    - docker build -t abhay14kumar/multi-nginx-demo ./nginx
    - docker build -t abhay14kumar/multi-server-demo ./server
    - docker build -t abhay14kumar/multi-worker-demo ./worker
    #login to the docker CLI

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push the image to docker hub

    - docker push abhay14kumar/multi-client-demo
    - docker push abhay14kumar/multi-nginx-demo
    - docker push abhay14kumar/multi-server-demo
    - docker push abhay14kumar/multi-worker-demo

